@startuml inmobiliaria_angel

class Propietario {
    - IdPropietario: Int
    - Nombre: String
    - Apellido: String
    - Dni: String
    - Telefono: String
    - Email: String
    - Clave: String
}

@enduml
